version: '3.3'

services:
  apache:
    build: ./php
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./www:/var/www/html
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: hw_db
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
